# Generated by Django 4.1.2 on 2024-07-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('nom_usuario', models.CharField(max_length=50)),
                ('p_nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=3)),
            ],
        ),
    ]
