# Generated by Django 4.1.2 on 2024-07-01 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('id_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.categoria')),
            ],
        ),
    ]
