# Generated by Django 4.1.2 on 2024-07-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_venta',
            field=models.BooleanField(default=False),
        ),
    ]
