# Generated by Django 4.1.2 on 2024-07-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_producto_en_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nom_usuario',
            new_name='username',
        ),
    ]
