# Generated by Django 4.1.2 on 2024-07-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_datos_usuario_remove_pedido_usuario_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos_Usuario',
        ),
    ]
