# Generated by Django 5.0.6 on 2024-07-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_delete_datos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_prod',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
